version: '3'
services:
  movies-front:
    # completa esta seccion, lee el archivo README en la carpeta movies-front
    container_name: front
    build:
      context: ./movies-front
      dockerfile: Dockerfile
    ports:
      - ${REACT_PORT}:${REACT_PORT}
    expose:
      - ${REACT_PORT}  
    environment:
      - REACT_PORT
      - REACT_APP_API_URI
    volumes:
      - ./movies-front:/usr/app
      - /usr/app/node_modules
    depends_on: 
    # de que servicio depende el frontend?
      - movies-api
    command: npm start



  movies-api:
    # completa esta seccion, lee el archivo README en la carpeta movies-api
    container_name: back
    build:
      context: ./movies-api
      dockerfile: Dockerfile
    ports:
      - ${BIND_PORT}:${BIND_PORT}
    expose:
      - ${BIND_IP}
    environment:
      - BIND_IP
      - BIND_PORT
      - POSTGRES_SERVER
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      postgres:
        condition: service_healthy
    command: /movies-api -b ${BIND_IP} -p ${BIND_PORT}



  postgres:
    container_name: dbserver
    image: postgres:15.3
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3      


  flyway:
    image: flyway/flyway:latest
    container_name: migration_flyway
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
      - FLYWAY_GROUP=true
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./sql_migrations:/flyway/sql
    depends_on:
      - postgres
